package ph.com.gs3.loyaltystore.models.sqlite.dao;

import com.google.gson.annotations.SerializedName;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CASH_RETURN".
 */
public class CashReturn {

    private Long id;
    private Long store_id;
    private String type;
    private String cash_type;
    private Float amount;
    private String remarks;
    private String deposited_to_bank;
    private java.util.Date time_of_deposit;
    private String Image;
    private String status;
    private Boolean is_synced;
    private java.util.Date date_created;
     @SerializedName("txt_approver")
    private String approver;

    public CashReturn() {
    }

    public CashReturn(Long id) {
        this.id = id;
    }

    public CashReturn(Long id, Long store_id, String type, String cash_type, Float amount, String remarks, String deposited_to_bank, java.util.Date time_of_deposit, String Image, String status, Boolean is_synced, java.util.Date date_created, String approver) {
        this.id = id;
        this.store_id = store_id;
        this.type = type;
        this.cash_type = cash_type;
        this.amount = amount;
        this.remarks = remarks;
        this.deposited_to_bank = deposited_to_bank;
        this.time_of_deposit = time_of_deposit;
        this.Image = Image;
        this.status = status;
        this.is_synced = is_synced;
        this.date_created = date_created;
        this.approver = approver;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getStore_id() {
        return store_id;
    }

    public void setStore_id(Long store_id) {
        this.store_id = store_id;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getCash_type() {
        return cash_type;
    }

    public void setCash_type(String cash_type) {
        this.cash_type = cash_type;
    }

    public Float getAmount() {
        return amount;
    }

    public void setAmount(Float amount) {
        this.amount = amount;
    }

    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public String getDeposited_to_bank() {
        return deposited_to_bank;
    }

    public void setDeposited_to_bank(String deposited_to_bank) {
        this.deposited_to_bank = deposited_to_bank;
    }

    public java.util.Date getTime_of_deposit() {
        return time_of_deposit;
    }

    public void setTime_of_deposit(java.util.Date time_of_deposit) {
        this.time_of_deposit = time_of_deposit;
    }

    public String getImage() {
        return Image;
    }

    public void setImage(String Image) {
        this.Image = Image;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Boolean getIs_synced() {
        return is_synced;
    }

    public void setIs_synced(Boolean is_synced) {
        this.is_synced = is_synced;
    }

    public java.util.Date getDate_created() {
        return date_created;
    }

    public void setDate_created(java.util.Date date_created) {
        this.date_created = date_created;
    }

    public String getApprover() {
        return approver;
    }

    public void setApprover(String approver) {
        this.approver = approver;
    }

}
