package ph.com.gs3.loyaltystore.models.sqlite.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CASH_RETURN".
 */
public class CashReturn {

    private Long id;
    private Long store_id;
    private String item;
    private String type;
    private Float amount;
    private String remarks;
    private String deposited_to_bank;
    private java.util.Date time_of_deposit;
    private String Image;
    private Boolean is_synced;

    public CashReturn() {
    }

    public CashReturn(Long id) {
        this.id = id;
    }

    public CashReturn(Long id, Long store_id, String item, String type, Float amount, String remarks, String deposited_to_bank, java.util.Date time_of_deposit, String Image, Boolean is_synced) {
        this.id = id;
        this.store_id = store_id;
        this.item = item;
        this.type = type;
        this.amount = amount;
        this.remarks = remarks;
        this.deposited_to_bank = deposited_to_bank;
        this.time_of_deposit = time_of_deposit;
        this.Image = Image;
        this.is_synced = is_synced;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getStore_id() {
        return store_id;
    }

    public void setStore_id(Long store_id) {
        this.store_id = store_id;
    }

    public String getItem() {
        return item;
    }

    public void setItem(String item) {
        this.item = item;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Float getAmount() {
        return amount;
    }

    public void setAmount(Float amount) {
        this.amount = amount;
    }

    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public String getDeposited_to_bank() {
        return deposited_to_bank;
    }

    public void setDeposited_to_bank(String deposited_to_bank) {
        this.deposited_to_bank = deposited_to_bank;
    }

    public java.util.Date getTime_of_deposit() {
        return time_of_deposit;
    }

    public void setTime_of_deposit(java.util.Date time_of_deposit) {
        this.time_of_deposit = time_of_deposit;
    }

    public String getImage() {
        return Image;
    }

    public void setImage(String Image) {
        this.Image = Image;
    }

    public Boolean getIs_synced() {
        return is_synced;
    }

    public void setIs_synced(Boolean is_synced) {
        this.is_synced = is_synced;
    }

}
