package ph.com.gs3.loyaltystore.models.sqlite.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "EXPENSES".
 */
public class Expenses {

    private Long id;
    private Long store_id;
    private String description;
    private Float amount;
    private java.util.Date date;
    private Boolean is_synced;

    public Expenses() {
    }

    public Expenses(Long id) {
        this.id = id;
    }

    public Expenses(Long id, Long store_id, String description, Float amount, java.util.Date date, Boolean is_synced) {
        this.id = id;
        this.store_id = store_id;
        this.description = description;
        this.amount = amount;
        this.date = date;
        this.is_synced = is_synced;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getStore_id() {
        return store_id;
    }

    public void setStore_id(Long store_id) {
        this.store_id = store_id;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Float getAmount() {
        return amount;
    }

    public void setAmount(Float amount) {
        this.amount = amount;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public Boolean getIs_synced() {
        return is_synced;
    }

    public void setIs_synced(Boolean is_synced) {
        this.is_synced = is_synced;
    }

}
