package ph.com.gs3.loyaltystore.models.sqlite.dao;

import com.google.gson.annotations.SerializedName;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "EXPENSE_TYPE".
 */
public class ExpenseType {

     @SerializedName("ID")
    private Long id;
     @SerializedName("txt_expense")
    private String type;

    public ExpenseType() {
    }

    public ExpenseType(Long id) {
        this.id = id;
    }

    public ExpenseType(Long id, String type) {
        this.id = id;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

}
