package ph.com.gs3.loyaltystore.models.sqlite.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "INVENTORY".
 */
public class Inventory {

    private Long id;
    private Long product_id;
    private String name;
    private Float quantityExpected;
    private Float quantity;
    private java.util.Date created_at;

    public Inventory() {
    }

    public Inventory(Long id) {
        this.id = id;
    }

    public Inventory(Long id, Long product_id, String name, Float quantityExpected, Float quantity, java.util.Date created_at) {
        this.id = id;
        this.product_id = product_id;
        this.name = name;
        this.quantityExpected = quantityExpected;
        this.quantity = quantity;
        this.created_at = created_at;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getProduct_id() {
        return product_id;
    }

    public void setProduct_id(Long product_id) {
        this.product_id = product_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Float getQuantityExpected() {
        return quantityExpected;
    }

    public void setQuantityExpected(Float quantityExpected) {
        this.quantityExpected = quantityExpected;
    }

    public Float getQuantity() {
        return quantity;
    }

    public void setQuantity(Float quantity) {
        this.quantity = quantity;
    }

    public java.util.Date getCreated_at() {
        return created_at;
    }

    public void setCreated_at(java.util.Date created_at) {
        this.created_at = created_at;
    }

}
