package ph.com.gs3.loyaltystore.models.sqlite.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ITEM_RETURN".
 */
public class ItemReturn {

    private Long id;
    private Long store_id;
    private String type;
    private String product_name;
    private Float quantity;
    private String remarks;
    private String status;
    private Boolean is_synced;
    private java.util.Date date_created;

    public ItemReturn() {
    }

    public ItemReturn(Long id) {
        this.id = id;
    }

    public ItemReturn(Long id, Long store_id, String type, String product_name, Float quantity, String remarks, String status, Boolean is_synced, java.util.Date date_created) {
        this.id = id;
        this.store_id = store_id;
        this.type = type;
        this.product_name = product_name;
        this.quantity = quantity;
        this.remarks = remarks;
        this.status = status;
        this.is_synced = is_synced;
        this.date_created = date_created;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getStore_id() {
        return store_id;
    }

    public void setStore_id(Long store_id) {
        this.store_id = store_id;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getProduct_name() {
        return product_name;
    }

    public void setProduct_name(String product_name) {
        this.product_name = product_name;
    }

    public Float getQuantity() {
        return quantity;
    }

    public void setQuantity(Float quantity) {
        this.quantity = quantity;
    }

    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Boolean getIs_synced() {
        return is_synced;
    }

    public void setIs_synced(Boolean is_synced) {
        this.is_synced = is_synced;
    }

    public java.util.Date getDate_created() {
        return date_created;
    }

    public void setDate_created(java.util.Date date_created) {
        this.date_created = date_created;
    }

}
