package ph.com.gs3.loyaltystore.models.sqlite.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ITEM_RETURN".
 */
public class ItemReturn {

    private Long id;
    private Long store_id;
    private String item;
    private String product_name;
    private Float quantity;
    private String remarks;
    private Boolean is_synced;

    public ItemReturn() {
    }

    public ItemReturn(Long id) {
        this.id = id;
    }

    public ItemReturn(Long id, Long store_id, String item, String product_name, Float quantity, String remarks, Boolean is_synced) {
        this.id = id;
        this.store_id = store_id;
        this.item = item;
        this.product_name = product_name;
        this.quantity = quantity;
        this.remarks = remarks;
        this.is_synced = is_synced;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getStore_id() {
        return store_id;
    }

    public void setStore_id(Long store_id) {
        this.store_id = store_id;
    }

    public String getItem() {
        return item;
    }

    public void setItem(String item) {
        this.item = item;
    }

    public String getProduct_name() {
        return product_name;
    }

    public void setProduct_name(String product_name) {
        this.product_name = product_name;
    }

    public Float getQuantity() {
        return quantity;
    }

    public void setQuantity(Float quantity) {
        this.quantity = quantity;
    }

    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public Boolean getIs_synced() {
        return is_synced;
    }

    public void setIs_synced(Boolean is_synced) {
        this.is_synced = is_synced;
    }

}
