package ph.com.gs3.loyaltystore.models.sqlite.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ITEM_STOCK_COUNT".
 */
public class ItemStockCount {

    private Long id;
    private Long store_id;
    private Long product_id;
    private String name;
    private Double expectedQuantity;
    private Double quantity;
    private String remarks;
    private java.util.Date date_counted;
    private Boolean is_synced;

    public ItemStockCount() {
    }

    public ItemStockCount(Long id) {
        this.id = id;
    }

    public ItemStockCount(Long id, Long store_id, Long product_id, String name, Double expectedQuantity, Double quantity, String remarks, java.util.Date date_counted, Boolean is_synced) {
        this.id = id;
        this.store_id = store_id;
        this.product_id = product_id;
        this.name = name;
        this.expectedQuantity = expectedQuantity;
        this.quantity = quantity;
        this.remarks = remarks;
        this.date_counted = date_counted;
        this.is_synced = is_synced;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getStore_id() {
        return store_id;
    }

    public void setStore_id(Long store_id) {
        this.store_id = store_id;
    }

    public Long getProduct_id() {
        return product_id;
    }

    public void setProduct_id(Long product_id) {
        this.product_id = product_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Double getExpectedQuantity() {
        return expectedQuantity;
    }

    public void setExpectedQuantity(Double expectedQuantity) {
        this.expectedQuantity = expectedQuantity;
    }

    public Double getQuantity() {
        return quantity;
    }

    public void setQuantity(Double quantity) {
        this.quantity = quantity;
    }

    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public java.util.Date getDate_counted() {
        return date_counted;
    }

    public void setDate_counted(java.util.Date date_counted) {
        this.date_counted = date_counted;
    }

    public Boolean getIs_synced() {
        return is_synced;
    }

    public void setIs_synced(Boolean is_synced) {
        this.is_synced = is_synced;
    }

}
