package ph.com.gs3.loyaltystore.models.sqlite.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ITEMS_RETURN".
 */
public class ItemsReturn {

    private Long id;
    private String item;
    private Long product_id;
    private Float quantity;
    private String remarks;

    public ItemsReturn() {
    }

    public ItemsReturn(Long id) {
        this.id = id;
    }

    public ItemsReturn(Long id, String item, Long product_id, Float quantity, String remarks) {
        this.id = id;
        this.item = item;
        this.product_id = product_id;
        this.quantity = quantity;
        this.remarks = remarks;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getItem() {
        return item;
    }

    public void setItem(String item) {
        this.item = item;
    }

    public Long getProduct_id() {
        return product_id;
    }

    public void setProduct_id(Long product_id) {
        this.product_id = product_id;
    }

    public Float getQuantity() {
        return quantity;
    }

    public void setQuantity(Float quantity) {
        this.quantity = quantity;
    }

    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

}
