package ph.com.gs3.loyaltystore.models.sqlite.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ITEM_INVENTORY".
 */
public class ItemInventory {

    private Long id;
    private Long store_id;
    private Long product_id;
    private String name;
    private Double quantity;
    private Boolean is_updated;

    public ItemInventory() {
    }

    public ItemInventory(Long id) {
        this.id = id;
    }

    public ItemInventory(Long id, Long store_id, Long product_id, String name, Double quantity, Boolean is_updated) {
        this.id = id;
        this.store_id = store_id;
        this.product_id = product_id;
        this.name = name;
        this.quantity = quantity;
        this.is_updated = is_updated;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getStore_id() {
        return store_id;
    }

    public void setStore_id(Long store_id) {
        this.store_id = store_id;
    }

    public Long getProduct_id() {
        return product_id;
    }

    public void setProduct_id(Long product_id) {
        this.product_id = product_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Double getQuantity() {
        return quantity;
    }

    public void setQuantity(Double quantity) {
        this.quantity = quantity;
    }

    public Boolean getIs_updated() {
        return is_updated;
    }

    public void setIs_updated(Boolean is_updated) {
        this.is_updated = is_updated;
    }

}
