package ph.com.gs3.loyaltystore.models.sqlite.dao;

import com.google.gson.annotations.SerializedName;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PRODUCT_BREAKDOWN".
 */
public class ProductBreakdown {

     @SerializedName("ID")
    private Long id;
     @SerializedName("txt_id")
    private Long product_id;
     @SerializedName("TS")
    private String ts;
     @SerializedName("txt_quantity")
    private Double quantity;
     @SerializedName("txt_description")
    private String name;

    public ProductBreakdown() {
    }

    public ProductBreakdown(Long id) {
        this.id = id;
    }

    public ProductBreakdown(Long id, Long product_id, String ts, Double quantity, String name) {
        this.id = id;
        this.product_id = product_id;
        this.ts = ts;
        this.quantity = quantity;
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getProduct_id() {
        return product_id;
    }

    public void setProduct_id(Long product_id) {
        this.product_id = product_id;
    }

    public String getTs() {
        return ts;
    }

    public void setTs(String ts) {
        this.ts = ts;
    }

    public Double getQuantity() {
        return quantity;
    }

    public void setQuantity(Double quantity) {
        this.quantity = quantity;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
