package ph.com.gs3.loyaltystore.models.sqlite.dao;

import com.google.gson.annotations.SerializedName;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PRODUCT_DELIVERY".
 */
public class ProductDelivery {

    private Long id;
     @SerializedName("rad_type")
    private String distribution_type;
    private Long product_id;
     @SerializedName("txt_cash")
    private Float cash;
    private String name;
    private Long delivered_to_store_id;
    private String delivered_to_store_name;
    private Integer delivered_by_agent_id;
    private String delivered_by_agent_name;
    private Double quantity;
    private java.util.Date date_delivered;
    private String status;
    private Boolean is_synced;

    public ProductDelivery() {
    }

    public ProductDelivery(Long id) {
        this.id = id;
    }

    public ProductDelivery(Long id, String distribution_type, Long product_id, Float cash, String name, Long delivered_to_store_id, String delivered_to_store_name, Integer delivered_by_agent_id, String delivered_by_agent_name, Double quantity, java.util.Date date_delivered, String status, Boolean is_synced) {
        this.id = id;
        this.distribution_type = distribution_type;
        this.product_id = product_id;
        this.cash = cash;
        this.name = name;
        this.delivered_to_store_id = delivered_to_store_id;
        this.delivered_to_store_name = delivered_to_store_name;
        this.delivered_by_agent_id = delivered_by_agent_id;
        this.delivered_by_agent_name = delivered_by_agent_name;
        this.quantity = quantity;
        this.date_delivered = date_delivered;
        this.status = status;
        this.is_synced = is_synced;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDistribution_type() {
        return distribution_type;
    }

    public void setDistribution_type(String distribution_type) {
        this.distribution_type = distribution_type;
    }

    public Long getProduct_id() {
        return product_id;
    }

    public void setProduct_id(Long product_id) {
        this.product_id = product_id;
    }

    public Float getCash() {
        return cash;
    }

    public void setCash(Float cash) {
        this.cash = cash;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getDelivered_to_store_id() {
        return delivered_to_store_id;
    }

    public void setDelivered_to_store_id(Long delivered_to_store_id) {
        this.delivered_to_store_id = delivered_to_store_id;
    }

    public String getDelivered_to_store_name() {
        return delivered_to_store_name;
    }

    public void setDelivered_to_store_name(String delivered_to_store_name) {
        this.delivered_to_store_name = delivered_to_store_name;
    }

    public Integer getDelivered_by_agent_id() {
        return delivered_by_agent_id;
    }

    public void setDelivered_by_agent_id(Integer delivered_by_agent_id) {
        this.delivered_by_agent_id = delivered_by_agent_id;
    }

    public String getDelivered_by_agent_name() {
        return delivered_by_agent_name;
    }

    public void setDelivered_by_agent_name(String delivered_by_agent_name) {
        this.delivered_by_agent_name = delivered_by_agent_name;
    }

    public Double getQuantity() {
        return quantity;
    }

    public void setQuantity(Double quantity) {
        this.quantity = quantity;
    }

    public java.util.Date getDate_delivered() {
        return date_delivered;
    }

    public void setDate_delivered(java.util.Date date_delivered) {
        this.date_delivered = date_delivered;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Boolean getIs_synced() {
        return is_synced;
    }

    public void setIs_synced(Boolean is_synced) {
        this.is_synced = is_synced;
    }

}
