package ph.com.gs3.loyaltystore.models.sqlite.dao;

import com.google.gson.annotations.SerializedName;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PRODUCT_FOR_DELIVERY".
 */
public class ProductForDelivery {

    private Long id;
    private Long product_id;
    private String track_no;
    private String name;
    private Double quantity;
    private String pick_bom;
     @SerializedName("Status")
    private String status;
     @SerializedName("txt_cash")
    private Double cash;
     @SerializedName("rad_type")
    private String distribution_type;
    private java.util.Date date_created;
     @SerializedName("txt_received")
    private Double quantity_received;
     @SerializedName("dt_received")
    private java.util.Date date_received;
     @SerializedName("txt_branch_id")
    private Long branch_id;
     @SerializedName("pick_branch")
    private String branch;

    public ProductForDelivery() {
    }

    public ProductForDelivery(Long id) {
        this.id = id;
    }

    public ProductForDelivery(Long id, Long product_id, String track_no, String name, Double quantity, String pick_bom, String status, Double cash, String distribution_type, java.util.Date date_created, Double quantity_received, java.util.Date date_received, Long branch_id, String branch) {
        this.id = id;
        this.product_id = product_id;
        this.track_no = track_no;
        this.name = name;
        this.quantity = quantity;
        this.pick_bom = pick_bom;
        this.status = status;
        this.cash = cash;
        this.distribution_type = distribution_type;
        this.date_created = date_created;
        this.quantity_received = quantity_received;
        this.date_received = date_received;
        this.branch_id = branch_id;
        this.branch = branch;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getProduct_id() {
        return product_id;
    }

    public void setProduct_id(Long product_id) {
        this.product_id = product_id;
    }

    public String getTrack_no() {
        return track_no;
    }

    public void setTrack_no(String track_no) {
        this.track_no = track_no;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Double getQuantity() {
        return quantity;
    }

    public void setQuantity(Double quantity) {
        this.quantity = quantity;
    }

    public String getPick_bom() {
        return pick_bom;
    }

    public void setPick_bom(String pick_bom) {
        this.pick_bom = pick_bom;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Double getCash() {
        return cash;
    }

    public void setCash(Double cash) {
        this.cash = cash;
    }

    public String getDistribution_type() {
        return distribution_type;
    }

    public void setDistribution_type(String distribution_type) {
        this.distribution_type = distribution_type;
    }

    public java.util.Date getDate_created() {
        return date_created;
    }

    public void setDate_created(java.util.Date date_created) {
        this.date_created = date_created;
    }

    public Double getQuantity_received() {
        return quantity_received;
    }

    public void setQuantity_received(Double quantity_received) {
        this.quantity_received = quantity_received;
    }

    public java.util.Date getDate_received() {
        return date_received;
    }

    public void setDate_received(java.util.Date date_received) {
        this.date_received = date_received;
    }

    public Long getBranch_id() {
        return branch_id;
    }

    public void setBranch_id(Long branch_id) {
        this.branch_id = branch_id;
    }

    public String getBranch() {
        return branch;
    }

    public void setBranch(String branch) {
        this.branch = branch;
    }

}
