package ph.com.gs3.loyaltystore.models.sqlite.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SALES".
 */
public class Sales {

    private Long id;
    private Integer store_id;
    private Long customer_id;
    private Float amount;
    private Float total_discount;
    private java.util.Date transacion_date;
    private Boolean is_synced;

    public Sales() {
    }

    public Sales(Long id) {
        this.id = id;
    }

    public Sales(Long id, Integer store_id, Long customer_id, Float amount, Float total_discount, java.util.Date transacion_date, Boolean is_synced) {
        this.id = id;
        this.store_id = store_id;
        this.customer_id = customer_id;
        this.amount = amount;
        this.total_discount = total_discount;
        this.transacion_date = transacion_date;
        this.is_synced = is_synced;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getStore_id() {
        return store_id;
    }

    public void setStore_id(Integer store_id) {
        this.store_id = store_id;
    }

    public Long getCustomer_id() {
        return customer_id;
    }

    public void setCustomer_id(Long customer_id) {
        this.customer_id = customer_id;
    }

    public Float getAmount() {
        return amount;
    }

    public void setAmount(Float amount) {
        this.amount = amount;
    }

    public Float getTotal_discount() {
        return total_discount;
    }

    public void setTotal_discount(Float total_discount) {
        this.total_discount = total_discount;
    }

    public java.util.Date getTransacion_date() {
        return transacion_date;
    }

    public void setTransacion_date(java.util.Date transacion_date) {
        this.transacion_date = transacion_date;
    }

    public Boolean getIs_synced() {
        return is_synced;
    }

    public void setIs_synced(Boolean is_synced) {
        this.is_synced = is_synced;
    }

}
