package ph.com.gs3.loyaltystore.models.sqlite.dao;

import com.google.gson.annotations.SerializedName;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SALES_PRODUCT".
 */
public class SalesProduct {

    private Long id;
    private String sales_transaction_number;
    private Long product_id;
     @SerializedName("product_name")
    private String name;
    private Integer quantity;
    private Float sub_total;
    private String sale_type;
    private String promo_code;
    private java.util.Date transaction_date;
    private Boolean is_returned;

    public SalesProduct() {
    }

    public SalesProduct(Long id) {
        this.id = id;
    }

    public SalesProduct(Long id, String sales_transaction_number, Long product_id, String name, Integer quantity, Float sub_total, String sale_type, String promo_code, java.util.Date transaction_date, Boolean is_returned) {
        this.id = id;
        this.sales_transaction_number = sales_transaction_number;
        this.product_id = product_id;
        this.name = name;
        this.quantity = quantity;
        this.sub_total = sub_total;
        this.sale_type = sale_type;
        this.promo_code = promo_code;
        this.transaction_date = transaction_date;
        this.is_returned = is_returned;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSales_transaction_number() {
        return sales_transaction_number;
    }

    public void setSales_transaction_number(String sales_transaction_number) {
        this.sales_transaction_number = sales_transaction_number;
    }

    public Long getProduct_id() {
        return product_id;
    }

    public void setProduct_id(Long product_id) {
        this.product_id = product_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getQuantity() {
        return quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    public Float getSub_total() {
        return sub_total;
    }

    public void setSub_total(Float sub_total) {
        this.sub_total = sub_total;
    }

    public String getSale_type() {
        return sale_type;
    }

    public void setSale_type(String sale_type) {
        this.sale_type = sale_type;
    }

    public String getPromo_code() {
        return promo_code;
    }

    public void setPromo_code(String promo_code) {
        this.promo_code = promo_code;
    }

    public java.util.Date getTransaction_date() {
        return transaction_date;
    }

    public void setTransaction_date(java.util.Date transaction_date) {
        this.transaction_date = transaction_date;
    }

    public Boolean getIs_returned() {
        return is_returned;
    }

    public void setIs_returned(Boolean is_returned) {
        this.is_returned = is_returned;
    }

}
