package ph.com.gs3.loyaltystore.models.sqlite.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SALES_HAS_REWARD".
 */
public class SalesHasReward {

    private Long id;
    private Long sales_id;
    private Long reward_id;

    public SalesHasReward() {
    }

    public SalesHasReward(Long id) {
        this.id = id;
    }

    public SalesHasReward(Long id, Long sales_id, Long reward_id) {
        this.id = id;
        this.sales_id = sales_id;
        this.reward_id = reward_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getSales_id() {
        return sales_id;
    }

    public void setSales_id(Long sales_id) {
        this.sales_id = sales_id;
    }

    public Long getReward_id() {
        return reward_id;
    }

    public void setReward_id(Long reward_id) {
        this.reward_id = reward_id;
    }

}
