package ph.com.gs3.loyaltystore.models.sqlite.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SALES_PRODUCT".
 */
public class SalesProduct {

    private Long id;
    private String sales_transaction_number;
    private Long product_id;
    private Integer quantity;
    private Float sub_total;
    private String sale_type;

    public SalesProduct() {
    }

    public SalesProduct(Long id) {
        this.id = id;
    }

    public SalesProduct(Long id, String sales_transaction_number, Long product_id, Integer quantity, Float sub_total, String sale_type) {
        this.id = id;
        this.sales_transaction_number = sales_transaction_number;
        this.product_id = product_id;
        this.quantity = quantity;
        this.sub_total = sub_total;
        this.sale_type = sale_type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSales_transaction_number() {
        return sales_transaction_number;
    }

    public void setSales_transaction_number(String sales_transaction_number) {
        this.sales_transaction_number = sales_transaction_number;
    }

    public Long getProduct_id() {
        return product_id;
    }

    public void setProduct_id(Long product_id) {
        this.product_id = product_id;
    }

    public Integer getQuantity() {
        return quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    public Float getSub_total() {
        return sub_total;
    }

    public void setSub_total(Float sub_total) {
        this.sub_total = sub_total;
    }

    public String getSale_type() {
        return sale_type;
    }

    public void setSale_type(String sale_type) {
        this.sale_type = sale_type;
    }

}
