package ph.com.gs3.loyaltystore.models.sqlite.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SALES_HAS_REWARD".
 */
public class SalesHasReward {

    private Long id;
    private Long reward_id;
    private String sales_transaction_number;

    public SalesHasReward() {
    }

    public SalesHasReward(Long id) {
        this.id = id;
    }

    public SalesHasReward(Long id, Long reward_id, String sales_transaction_number) {
        this.id = id;
        this.reward_id = reward_id;
        this.sales_transaction_number = sales_transaction_number;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getReward_id() {
        return reward_id;
    }

    public void setReward_id(Long reward_id) {
        this.reward_id = reward_id;
    }

    public String getSales_transaction_number() {
        return sales_transaction_number;
    }

    public void setSales_transaction_number(String sales_transaction_number) {
        this.sales_transaction_number = sales_transaction_number;
    }

}
